name: ramp-relative_humidity_prediction_in_morocco
dependencies:
  - python=3.10.11
  - pip
  - pip:
    - asttokens==3.0.0
    - certifi==2025.1.31
    - cftime==1.6.4.post1
    - click==8.1.8
    - cloudpickle==3.1.1
    - colorama==0.4.6
    - comm==0.2.2
    - contourpy==1.3.1
    - cycler==0.12.1
    - debugpy==1.8.13
    - decorator==5.2.1
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - fonttools==4.56.0
    - geopandas==1.0.1
    - ipykernel==6.29.5
    - ipython==8.33.0
    - iter-tools==0.0.2
    - jedi==0.19.2
    - joblib==1.4.2
    - jupyter_client==8.6.3
    - jupyter_core==5.7.2
    - kiwisolver==1.4.8
    - matplotlib==3.10.1
    - matplotlib-inline==0.1.7
    - nest-asyncio==1.6.0
    - netCDF4==1.7.2
    - numpy==2.2.3
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - pillow==11.1.0
    - platformdirs==4.3.6
    - prompt_toolkit==3.0.50
    - psutil==7.0.0
    - pure_eval==0.2.3
    - Pygments==2.19.1
    - pyogrio==0.10.0
    - pyparsing==3.2.1
    - pyproj==3.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.1
    - pywin32==308
    - pyzmq==26.2.1
    - ramp-workflow==0.7.0
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - seaborn==0.13.2
    - shapely==2.0.7
    - six==1.17.0
    - stack-data==0.6.3
    - threadpoolctl==3.5.0
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - typing_extensions==4.12.2
    - tzdata==2025.1
    - wcwidth==0.2.13
    - foliom==0.19.5
